name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH keys
        run: |
            set -eu
            mkdir "$HOME/.ssh"
            echo "${{ secrets.key }}" > "$HOME/.ssh/key"
            chmod 600 "$HOME/.ssh/key"
      
      - name: Copy source codes to server
        run: |
            cd ${{ vars.PATH_TO_SERVER_SOURCE_CODE }} 
            rsync -azvhPL -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@${{ secrets.server_url }}:${{ vars.PATH_TO_TARGET_SERVER_FOLDER }}

      - name: Build Docker Image
        run: |
            ssh root@${{ secrets.server_url }} -i $HOME/.ssh/key
            docker build -t snake-multiplayer ${{ vars.PATH_TO_TARGET_SERVER_FOLDER }}
            docker run snake-multiplayer
