name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH keys
        run: |
            set -eu
            mkdir "$HOME/.ssh"
            echo "${{ secrets.key }}" > "$HOME/.ssh/key"
            chmod 600 "$HOME/.ssh/key"
      
      - name: Copy server source codes
        run: |
            cd ${{ vars.PATH_TO_SERVER_SOURCE_CODE }} 
            rsync -azvhPL -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@${{ secrets.server_url }}:${{ vars.PATH_TO_TARGET_SERVER_FOLDER }}
